name: Update Timestamp

permissions:
  contents: write

on:
  push:
    paths:
      - status.json

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set last_updated timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Updating timestamp to $TIMESTAMP"
          sed -i.bak 's/"last_updated": *".*"/"last_updated": "'"$TIMESTAMP"'"/' status.json
          cat status.json
          git diff

      - name: Commit updated file if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet; then
            git commit -am "Auto-update last_updated timestamp"
            git push
          else
            echo "No changes to commit."
          fi
